import { FeatureHero } from "@/components/MarketingUI/FeatureHero";
import { FeatureHighlight } from "@/components/MarketingUI/FeatureHighlight";
import { Metadata } from "next";
import { HeaderPublic } from "@/components/HeaderPublic";
import { TitleSeparator } from "@/components/MarketingUI/TitleSeparator";
import { CtaSeparator } from "@/components/MarketingUI/CtaSeparator";
import { FaqSection } from "@/components/FaqSection";

const faqs = [
  {
    question:
      "How does the unlimited image generation feature work for team members?",
    answer:
      "With Wielded, your entire team can generate up to 50 images per minute collectively, using integration with OpenAI's Dall-E 3 API. The actual limit depends on the usage tier of your OpenAI API account.",
  },
  {
    question:
      "Is there a limit on the number of images a team can generate using Dall-E 3?",
    answer:
      "No, there is no limit on the number of images. Wielded offers unlimited image generation, allowing your team to create as many images as needed for your projects.",
  },
  {
    question:
      "Can every team member access Dall-E 3 without an individual subscription on OpenAI?",
    answer:
      "Yes, each team member has access to Dall-E 3 without the need for an individual subscription to ChatGPT Plus. Once your team is set up with Wielded, everyone on your workspace can start generating images right away.",
  },
  {
    question:
      "How does Wielded offer granular controls on the style of generated images?",
    answer:
      "Wielded lets users start with a simple prompt that is automatically transformed into a detailed prompt, which is shown to the user. They can use the original vague prompt for varied creative outputs or the detailed prompt for greater consistency between images.",
  },
  {
    question:
      "How can I find a specific image that was created by my team in the past?",
    answer:
      "Our gallery feature allows you to view all created images at a glance. You can use the visual search to find images or the text search function to quickly locate past creations.",
  },
  {
    question: "Can team members generate images in parallel using Wielded?",
    answer:
      "Absolutely, team members can simultaneously request image generations, which allows for parallel creation of up to 50 images per minute as per OpenAI's current API rate limits.",
  },
  {
    question:
      "Are there any additional costs for the image generation feature in Wielded?",
    answer:
      "Image generation with Dall-E 3 is included in your Wielded subscription. There are no additional for the feature. Do take note that API usage fees for OpenAI's Dall-E 3 API still apply.",
  },
  {
    question:
      "Is it possible to specify the artistic style of the images generated by Dall-E 3 in Wielded?",
    answer:
      "Yes, users can specify the style in their prompts between 'artistic' and 'realistic' in the app.",
  },
  {
    question:
      "How does Wielded ensure the quality of images generated with Dall-E 3?",
    answer:
      "Wielded uses the latest iteration of Dall-E 3, which has been trained to understand prompts and create high-quality images.",
  },
  {
    question:
      "Will there be training provided to use the Dall-E 3 feature within Wielded?",
    answer:
      "Wielded ensures that getting started with Dall-E 3 is intuitive. However, we do provide resources and guides to help users make the most out of the image generation features. For advanced training needs, contact our support team.",
  },
];

const Content = () => {
  return (
    <>
      <HeaderPublic />
      <FeatureHero
        heading="Limitless Image Generation with Dall-E 3"
        subheading="Unleash creativity across your team without worrying about rate limits. Turn every team member into a digital artist with Wielded."
        videoUrl="https://www.youtube-nocookie.com/embed/rP7_STmtiHc?si=vdTBCvZQGDJakA3G&controls=0"
        source="image-generation-with-dalle3"
      />
      <TitleSeparator title="Creativity without boundaries" />
      <FeatureHighlight
        heading="Dall-E 3 Access for the Entire Team"
        subheading="Forget the hassle of individual subscriptions"
        description="Every team member can harness the capability of Dall-E 3 without individual subscription constraints. Generate high-quality images as a team, and elevate your project visuals without limitations."
        imageUrl="/assets/images/demo-generating-image-with-dalle-3.png"
        imageAlt="Team using Dall-E 3 for image generation"
      />
      <FeatureHighlight
        heading="Unlimited Image Generation"
        subheading="Maximizing productivity without hitting rate limits"
        description={`Create more, wait less. With Wielded, your team can generate up to 50 images per minute, bypassing the individual rate limits typically encountered. Refer to the OpenAI rate limits for more details.`}
        imageUrl="/assets/images/multiple-images-generated-by-dalle-3.png"
        imageAlt="Uninterrupted image generation with Dall-E 3"
      />
      <FeatureHighlight
        heading="Granular Style Controls"
        subheading="Control your creative output with simple and detailed prompts"
        description="Achieve the exact style your project requires. Start with a simple prompt and let Wielded refine it into a detailed one, offering you the option for creative exploration or consistent imagery."
        imageUrl="/assets/images/dalle-3-detailed-prompt-controls.png"
        imageAlt="Fine-tuning image generation with granular controls"
      />
      <FeatureHighlight
        heading="Your Creations at a Glance"
        subheading="Seamless visual and textual search"
        description="Easily browse through all generated images in our intuitive gallery view. Looking for something specific? Use the text search feature to quickly find your past creations."
        imageUrl="/assets/images/dalle-3-gallery-light.png"
        imageAlt="Searching through generated images in gallery"
      />
      <CtaSeparator
        title="Go unlimited with Wielded today."
        subtitle="Need help? Contact us."
        source="image-generation-with-dalle3"
      />
      <FaqSection faqs={faqs} className="my-10" />
    </>
  );
};

export default Content;

export const metadata: Metadata = {
  title: "Image Generation with Dall-E 3 - Wielded",
  description:
    "Leverage unlimited image generation for your team with Wielded's integration of Dall-E 3. Ensure brand consistency or let creativity fly with granular controls and an easy-to-search gallery.",
};
